### ISSUE TITLE
apg to fasta 

### ISSUE THREAD

**Issue by Rhia15** [sanger-tol/PretextView#25]
Hi, this is a great tool! I have managed to manually curate my map, however, I was was using the pretext_to_tpf.py script to convert my APG file into a fasta file and got this error. 

Traceback (most recent call last):
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 244, in <module>
    cli()
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/miniconda3/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/scripts/pretext_to_tpf.py", line 149, in cli
    build_asm.remap_to_input_assembly(prtxt_asm, input_asm)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 74, in remap_to_input_assembly
    self.cut_remaining_overhangs()
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 123, in cut_remaining_overhangs
    self.cut_fragments(fnd)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 143, in cut_fragments
    self.qc_sub_fragments(fnd, sub_fragments)
  File "/gpfs01/home/mbars7/yahs/pyrenaica_hap1/agp-tpf-utils/src/tola/assembly/build_assembly.py", line 187, in qc_sub_fragments
    raise ValueError(msg)
ValueError: Sum of fragment lengths 4_694_157 does not match orginal fragment length 4_707_000
Expecting 1 abutting sub fragments but got 0

I used the TPF file I generated before the manual curation and the apg file generated after, I was just wondering what it means by different fragment lengths? I am not sure where the fragments could have gone? 

Thank you very much.

**Comment by additive3** [comment]
Hi @Rhia15 

I'll take a look and get back to you regarding pretext_to_tpf.py error.

**Comment by Rhia15** [comment]
Hi, thank you very much! ah just to add I think it might be something to do with the layout of the agp file being outputted, I am trying to change the layout of it based on the test data provided (nearly done this i think), but this is the layout I got after saving it as an agp file in pretext, do you know why it's being outputted this way? Or if this is the correct format? :) Thank you!

This is a snippet: 
##agp-version   2.1
# DESCRIPTION: Generated by PretextView Version 0.2.5
# HiC MAP RESOLUTION: 12843.489777 bp/texel
Scaffold_1      1       23709082        1       W       scaffold_1      1       23709082        +
       Painted
Scaffold_2      1       24299882        1       W       scaffold_1      23709083        48008964
        +       Painted
Scaffold_3      1       1939366 1       W       scaffold_25     1       1939366 +       Painted
Scaffold_4      1       23015533        1       W       scaffold_2      1       23015533        +
       Painted
Scaffold_5      1       4559439 1       W       scaffold_17     154122  4713560 +       Painted
Scaffold_6      1       770609  1       W       scaffold_51     1       770609  +       Painted
Scaffold_7      1       796296  1       W       scaffold_46     1       796296  +       Painted
Scaffold_8      1       732078  1       W       scaffold_54     1       732078  +       Painted
Scaffold_9      1       475209  1       W       scaffold_61     1       475209  +       Painted
Scaffold_10     1       757765  1       W       scaffold_53     1       757765  +       Painted
Scaffold_11     1       22784351        1       W       scaffold_3      25687   22810037        +
       Painted
Scaffold_12     1       21050479        1       W       scaffold_4      1       21050479        +
       Painted
Scaffold_13     1       783452  1       W       scaffold_48     1       783452  +       Painted
Scaffold_14     1       1143071 1       W       scaffold_19     12844   1155914 +       Painted
Scaffold_15     1       1348567 1       W       scaffold_32     51374   1399940 +       Painted
Scaffold_16     1       2748506 1       W       scaffold_19     1155915 3904420 +       Painted


Am I right in thinking that the columns should be in a different order? 

Thank you!

**Comment by jgrg** [comment]
Hi. The AGP is fine. The AGP that PretextView generates has extra columns, described in the [agp-tpf-utils repository](https://github.com/sanger-tol/agp-tpf-utils?tab=readme-ov-file#agp).

The error is caused by an off-by-one-pixel error in your PretextView map.
From your error message: `4_707_000 - 4_694_157 = 12843` and 12843 is the resolution of your map.
When making an edit you have left behind a single pixel on the end of a scaffold. The single pixel is discarded during the remapping, and this internal consistency check made during cutting scaffolds notices it is missing from the rearranged scaffold.
I think there might be something more in the error message that would tell you which scaffold it is. Feel free to open an issue in [agp-tpf-utils](https://github.com/sanger-tol/agp-tpf-utils).
